// iHFormFields     ･   collection-view-boilerplate   ･     created by Garth Snyder   aka   gladiusKatana  ⚔️
import UIKit

var iHFormFields = [["",                                                                "",                     "",         "",     ""],
                    [" Your Vehicle\(headerTitleSpaces)",                               "Year ↕️",              "Make",     "Model", ""],
                    [" Did you lease it?\(headerTitleSpaces)",                          "Leased",               "Not Leased", "",   ""],
                    [" When did you buy or lease?\(headerTitleSpaces)",                 "Year ↕️",              "Month ↕️", "",     ""],
                    [" Main use of your vehicle\(headerTitleSpaces)",                   "Pleasure",             "Business", "",     ""],
                    [" Your daily commute (one way)\(headerTitleSpaces)",               "15 Km ↕️",             "",         "",     ""],
                    [" Annual distance\(headerTitleSpaces)",                            "8,000Km ↕️",           "",         "",     ""],
                    [" Does your vehicle have winter tires?\(headerTitleSpaces)",       "Yes",                  "No",       "",     ""],
                    [" Where is this vehicle parked at night?\(headerTitleSpaces)",     "Private driveway ↕️",  "",         "",     ""],
                    [" Coverage and Deductible Preferences\(headerTitleSpaces)",        "",                     "",         "",     ""],
                    [" Liability coverage\(headerTitleSpaces)",                         "",                     "",         "",     ""],
                    [" Collision deductible\(headerTitleSpaces)",                       "",                     "",         "",     ""],
                    [" Comprehensive deductible\(headerTitleSpaces)",                   "$300",                 "500",      "$1,000", "Decline"],
                    [" Loss of use\(headerTitleSpaces)",                                "Yes",                  "No",       "",     ""],
                    [" Rental car insurance\(headerTitleSpaces)",                       "Yes",                  "No",       "",     ""],
                    [" ",                                                               "",                     "",         "",     ""],
                    [" ",                                                               "",                     "",         "",     ""],
                    [" ",                                                               "",                     "",         "",     ""],
                    [" ",                                                               "",                     "",         "",     ""],
                    [" ",                                                               "",                     "",         "",     ""],
                    [" ",                                                               "",                     "",         "",     ""],
                    [" ",                                                               "",                     "",         "",     ""],
                    [" ",                                                               "",                     "",         "",     ""],
                    [" ",                                                               "",                     "",         "",     ""],
                    [" ",                                                               "",                     "",         "",     ""],
                    [" ",                                                               "",                     "",         "",     ""],
                    [" ",                                                               "",                     "",         "",     ""],
                    [" ",                                                               "",                     "",         "",     ""],
                    [" ",                                                               "",                     "",         "",     ""],
                    [" end\(headerTitleSpaces)",                                        "",                     "",         "",     ""]]


var boilerplateFormFieldMatrix = [[""], /// admittedly nerdy-sounding but descriptive nonetheless
    [" "],
    [" "],
    [" "],
    [" "],
    [" "],
    [" "],
    [" "],
    [" "],
    [" "],
    [" "],
    [" "],
    [" "],
    [" "],
    [" "],
    [" "],
    [" "],
    [" "],
    [" "],
    [" "],
    [" "],
    [" "],
    [" "],
    [" "],
    [" "],
    [" "],
    [" "],
    [" "],
    [" "],
    [" "]]
