// IHotlnColumn2    ･   collection-view-boilerplate   ･     created by Garth Snyder   aka   gladiusKatana  ⚔️
import UIKit

var insHotlineFormContentsTwo = ["",
                                 " Make ↕️",
                                 " Not Leased",
                                 " Month ↕️",
                                 " Business",
                                 " ",
                                 " ",
                                 " No",
                                 " ",
                                 " ",
                                 " $2 Million",
                                 " $1,000",
                                 " $500",
                                 " No",
                                 " No",
                                 " ",
                                 " ",
                                 " ",
                                 " ",
                                 " ",
                                 " ",
                                 " ",
                                 " ",
                                 " ",
                                 " ",
                                 " ",
                                 " ",
                                 " ",
                                 " ",
                                 " end"]

