// IHotlnColumn1    ･   collection-view-boilerplate   ･     created by Garth Snyder   aka   gladiusKatana  ⚔️
import UIKit

var insHotlineFormContentsOne = ["",
                                 " Year ↕️",
                                 " Leased",
                                 " Year ↕️",
                                 " Pleasure",
                                 " 0 Km ↕️",
                                 " 15,000 Km ↕️",
                                 " Yes",
                                 " Private Garage ↕️",
                                 " ",
                                 " $1 Million",
                                 " $500",
                                 " $300",
                                 " Yes",
                                 " Yes",
                                 " ",
                                 " ",
                                 " ",
                                 " ",
                                 " ",
                                 " ",
                                 " ",
                                 " ",
                                 " ",
                                 " ",
                                 " ",
                                 " ",
                                 " ",
                                 " ",
                                 " end"]
//⇕⇳⬍
