// IHotlnColumn0    ･   collection-view-boilerplate   ･     created by Garth Snyder   aka   gladiusKatana  ⚔️
import UIKit

var insHotlineHeaderTitles = ["",
                              " Your Vehicle\(headerTitleSpaces)",
                              " Did you lease it?\(headerTitleSpaces)",
                              " When did you buy or lease?\(headerTitleSpaces)",
                              " Main use of your vehicle\(headerTitleSpaces)",
                              " Your daily commute (one way)\(headerTitleSpaces)",
                              " Annual distance\(headerTitleSpaces)",
                              " Does your vehicle have winter tires?\(headerTitleSpaces)",
                              " Where is this vehicle parked at night?\(headerTitleSpaces)",
                              " Coverage and Deductible Preferences\(headerTitleSpaces)",
                              " Liability coverage\(headerTitleSpaces)",
                              " Collision deductible\(headerTitleSpaces)",
                              " Comprehensive deductible\(headerTitleSpaces)",
                              " Loss of use\(headerTitleSpaces)",
                              " Rental car insurance\(headerTitleSpaces)",
                              " ",
                              " ",
                              " ",
                              " ",
                              " ",
                              " ",
                              " ",
                              " ",
                              " ",
                              " ",
                              " ",
                              " ",
                              " ",
                              " ",
                              " end\(headerTitleSpaces)"]

var headerTitleSpaces = "   "
