// IHotlnColumn3    ･   collection-view-boilerplate   ･     created by Garth Snyder   aka   gladiusKatana  ⚔️
import UIKit

var insHotlineFormContentsThree = ["",
                                   " Model (type it in)",
                                   " ",
                                   " ",
                                   " ",
                                   " ",
                                   " ",
                                   " ",
                                   " ",
                                   " ",
                                   " ",
                                   " Decline",
                                   " $1,000",
                                   " ",
                                   " ",
                                   " ",
                                   " ",
                                   " ",
                                   " ",
                                   " ",
                                   " ",
                                   " ",
                                   " ",
                                   " ",
                                   " ",
                                   " ",
                                   " ",
                                   " ",
                                   " ",
                                   " end"]

