// IHotlnColumn0    ･   collection-view-boilerplate   ･     created by Garth Snyder   aka   gladiusKatana  ⚔️
import UIKit

var insHotlineHeaderTitles = ["",
                              " Your Vehicle",
                              " Did you lease it?",
                              " When did you buy or lease?",
                              " Main use of your vehicle",
                              " Your daily commute (one way)",
                              " Annual distance",
                              " Does your vehicle have winter tires?",
                              " Where is this vehicle parked at night?",
                              " Coverage and Deductible Preferences",
                              " Liability coverage",
                              " Collision deductible",
                              " Comprehensive deductible",
                              " Loss of use",
                              " Rental car insurance",
                              " ",
                              " ",
                              " ",
                              " ",
                              " ",
                              " ",
                              " ",
                              " ",
                              " ",
                              " ",
                              " ",
                              " ",
                              " ",
                              " ",
                              " ok"]

